#!/bin/sh

# =========
# Autostart
# =========
# Start key bindings
sxhkd &

#Mouse move focus 
bspc config focus_follows_pointer true	

# Start compositor
compton --experimental-backends &

# Start polkit agent
#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Start mouse
xsetroot -cursor_name left_ptr &

# Set wallpaper
#nitrogen --restore &

# Start status bar
bash /home/nic/.config/polybar/launch.sh &

# Start Spotify Fix Script
#bash /home/nic/.config/bspwm/spotify-script.sh &

# ==========
# Workspaces
# ==========
bspc monitor DP-2 -d Main Web Program Media Shite 
bspc monitor HDMI-0 -d VI VII VIII IX X

# =====
# Tiled
# =====
# Border width
bspc config border_width 0

# Gap between windows
bspc config window_gap  15

# Windows split ratio
bspc config split_ratio 0.5

# Rounded Corners?
bspc config border_radius 10

# =======
# Monocle
# =======
# Borders
bspc config borderless_monocle false

# Gap
bspc config gapless_monocle false

# ============
# Window Rules
# ============
bspc rule -a firefox       desktop=^2
bspc rule -a Spotify	   desktop=^4
bspc rule -a Gwe 		   desktop=^6
bspc rule -a Steam 		   desktop =^5

bspc rule -a Steam 		   state=floating
bspc rule -a URxvt:urxvt_keys_help state=floating
bspc rule -a "origin.exe"  state=floating
bspc rule -a "Wine"		   state=floating

# PyWal Colors 
# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
